In [1]:
#Implementation of DirectPOD method

import numpy as np

init_snapshots = np.array([[37., 40., 41., 49., 42., 46., 45., 48.], [40., 43., 47., 46., 41., 46., 45., 48.], [40., 41., 42., 45., 44., 46., 45., 47.]]).T
init_snapshots = np.array([[37., 40., 41., 49., 42., 46., 45., 48.], [40., 43., 47., 46., 41., 46., 45., 48.], [40., 41., 42., 45., 44., 46., 45., 47.]])


print("Initial snapshots:\n{}".format(init_snapshots))

m = init_snapshots.shape[0]  # Size of each snapshot
n = init_snapshots.shape[1]  # Number of snapshots
print("Size: ({}x{})".format(m, n))

mean_snapshot = np.average(init_snapshots, 1).reshape(m, -1)
print("Mean snapshot:\n{}".format(mean_snapshot))
snapshots = np.subtract(init_snapshots, mean_snapshot)

U, s, V = np.linalg.svd(snapshots, full_matrices=False)

print("\nU:\n{}\nS:\n{}\nV:\n{}\n".format(U, s, V))

rank = 3#8
dim = m - rank

S = np.diag(s)

if rank == m:
    fluctuation = np.dot(U, np.dot(S, V))
else:
    fluctuation = np.dot(U[:, :-dim], np.dot(S[:-dim, :-dim], V[:-dim, :]))

#print("Fluctuation:\n{}".format(fluctuation))

snap = 1
matrix_snap = mean_snapshot.flatten() + np.dot(U, np.dot(S, V)[:, snap])
print("Snapshot {}:\n{}".format(snap + 1, matrix_snap))
V = V.T
S = S.diagonal()
matrix_snap = mean_snapshot.flatten() + np.dot(U, V[snap]*S)
print("Snapshot {}:\n{}".format(snap + 1, matrix_snap))

reconstruction = mean_snapshot + fluctuation

print("\nReconstruction:\n{}".format(reconstruction))
equal = np.allclose(init_snapshots, reconstruction)
print("\nSame matrices: {}\n".format(equal))
if not equal:
    print("Difference:\n{}".format(reconstruction-init_snapshots))

Initial snapshots:
[[37. 40. 41. 49. 42. 46. 45. 48.]
 [40. 43. 47. 46. 41. 46. 45. 48.]
 [40. 41. 42. 45. 44. 46. 45. 47.]]
Size: (3x8)
Mean snapshot:
[[43.5 ]
 [44.5 ]
 [43.75]]

U:
[[-0.7759609   0.33566479 -0.53405414]
 [-0.45322276 -0.88555059  0.10192784]
 [-0.43871837  0.32113751  0.83928356]]
S:
[14.0033519   4.74678283  2.20775642]
V:
[[ 0.62331092  0.32864794  0.11244469 -0.39247868  0.18856495 -0.25757067
  -0.13846333 -0.46445583]
 [ 0.12616773 -0.15371022 -0.76157457  0.19365798  0.56379538  0.0491692
   0.09735937 -0.11486487]
 [-0.0609835  -0.26802416  0.05490131 -0.78600227  0.29629839  0.31984707
   0.13542579  0.30853738]]

Snapshot 2:
[40. 43. 41.]
Snapshot 2:
[40. 43. 41.]

Reconstruction:
[[37. 40. 41. 49. 42. 46. 45. 48.]
 [40. 43. 47. 46. 41. 46. 45. 48.]
 [40. 41. 42. 45. 44. 46. 45. 47.]]

Same matrices: True

