In [11]:
#Imports the entire numpy library. It's functions / methods by prefixing each call with np. as in NumPy library.
import numpy as np

#initialize transform of snapshot matrix "A^T"
init_snapshots = np.array([[37., 40., 41., 49., 42., 46., 45., 48.], [40., 43., 47., 46., 41., 46., 45., 48.], [40., 41., 42., 45., 44., 46., 45., 47.]]).T
#initialize Matrix 
init_snapshots = np.array([[37., 40., 41., 49., 42., 46., 45., 48.], [40., 43., 47., 46., 41., 46., 45., 48.], [40., 41., 42., 45., 44., 46., 45., 47.]])
 
#Print Initial snapshots
print("Initial snapshots:\n{}".format(init_snapshots)) 
 
m = init_snapshots.shape[0]  #whereas m = Size of each snapshot 
n = init_snapshots.shape[1]  #and n = Number of snapshots

#Print size of snapshots
print("Size: ({}x{})".format(m, n)) 
 
#Retrieve structure (anatomy) of the snapshot matrix by Singular Value Decomposition
mean_snapshot = np.average(init_snapshots, 1).reshape(m, -1)
#Print Retrieved structure
print("Mean snapshot:\n{}".format(mean_snapshot))
#subtract initial snapshot matrix by mean snapshot
snapshots = np.subtract(init_snapshots, mean_snapshot) 
 
#Singular Value Decomposition
U, s, V = np.linalg.svd(snapshots, full_matrices=False)
#U = m x n matrix of the orthonormal eigenvectors of AA^{T}              
#s =n x n diagonal matrix of the singular values which are the square roots of the eigenvalues of A^{T}A           
#V = transpose of a n x n matrix containing the orthonormal eigenvectors of A^{T}A 
print("\nU:\n{}\nS:\n{}\nV:\n{}\n".format(U, s, V)) # V = Print U, s & V matrices 
 
#define the rank 
rank = 3
#Size of each snapshot - rank 
dim = m - rank
#Extract a diagonal or construct a diagonal array  
S = np.diag(s)
 
#compares the equality of rank and m 
if rank == m:  
    fluctuation = np.dot(U, np.dot(S, V)) 
else: 
    fluctuation = np.dot(U[:, :-dim], np.dot(S[:-dim, :-dim], V[:-dim, :])) 
#print the flactuation 
print("Fluctuation:\n{}".format(fluctuation))
 
#Assigning value to the snap
snap = 1

#mean snapshot returns a copy of the array in one dimensional rather than in 2-D or a multi-dimensional array and add Dot product of two arrays of U with dot product product of s and V snap
matrix_snap = mean_snapshot.flatten() + np.dot(U, np.dot(S, V)[:, snap])
#do variable data formatting and print Snapshot
print("Snapshot {}:\n{}".format(snap + 1, matrix_snap)) 
V = V.T
#find a diagonal element from a given matrix and gives output as one dimensional matrix 
S = S.diagonal()
#mean snapshot returns a copy of the array in one dimensional rather than in 2-D or a multi-dimensional array and add Dot product of two arrays of U with dot product product of Vsnap and S
matrix_snap = mean_snapshot.flatten() + np.dot(U, V[snap]*S)
#do variable data formatting and print Snapshot
print("Snapshot {}:\n{}".format(snap + 1, matrix_snap))

#Reconstrction by adding mean snapshot matrix and fluctuation matix
reconstruction = mean_snapshot + fluctuation 

#print the reconstruction snapshot marix 
print("\nReconstruction:\n{}".format(reconstruction))
 
#compares the equality of reconstruction Snapshot marix and initialize Matrix, If same print as "Same matrices : true" otherwise  "Same matrices : false" 
equal = np.allclose(init_snapshots, reconstruction) 
print("\nSame matrices: {}\n".format(equal)) 
if not equal: 
    print("Difference:\n{}".format(reconstruction-init_snapshots)) 

Initial snapshots:
[[37. 40. 41. 49. 42. 46. 45. 48.]
 [40. 43. 47. 46. 41. 46. 45. 48.]
 [40. 41. 42. 45. 44. 46. 45. 47.]]
Size: (3x8)
Mean snapshot:
[[43.5 ]
 [44.5 ]
 [43.75]]

U:
[[-0.7759609   0.33566479 -0.53405414]
 [-0.45322276 -0.88555059  0.10192784]
 [-0.43871837  0.32113751  0.83928356]]
S:
[14.0033519   4.74678283  2.20775642]
V:
[[ 0.62331092  0.32864794  0.11244469 -0.39247868  0.18856495 -0.25757067
  -0.13846333 -0.46445583]
 [ 0.12616773 -0.15371022 -0.76157457  0.19365798  0.56379538  0.0491692
   0.09735937 -0.11486487]
 [-0.0609835  -0.26802416  0.05490131 -0.78600227  0.29629839  0.31984707
   0.13542579  0.30853738]]

Fluctuation:
[[-6.5  -3.5  -2.5   5.5  -1.5   2.5   1.5   4.5 ]
 [-4.5  -1.5   2.5   1.5  -3.5   1.5   0.5   3.5 ]
 [-3.75 -2.75 -1.75  1.25  0.25  2.25  1.25  3.25]]
Snapshot 2:
[40. 43. 41.]
Snapshot 2:
[40. 43. 41.]

Reconstruction:
[[37. 40. 41. 49. 42. 46. 45. 48.]
 [40. 43. 47. 46. 41. 46. 45. 48.]
 [40. 41. 42. 45. 44. 46. 45. 47.]]

Same ma